# Generated by Django 4.2.2 on 2023-07-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="typeUser",
            field=models.CharField(
                choices=[("user", "User"), ("seller", "Seller"), ("admin", "Admin")],
                default="user",
            ),
        ),
    ]
