# Generated by Django 4.2.2 on 2023-07-03 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_remove_address_user"),
        ("users", "0002_rename_isadm_user_isadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="address.address",
            ),
            preserve_default=False,
        ),
    ]
