# Generated by Django 4.2.2 on 2023-07-04 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_type_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="type_user",
            new_name="typeUser",
        ),
    ]
