# Generated by Django 4.2.3 on 2023-07-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_typeuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="typeUser",
            field=models.CharField(
                choices=[("user", "User"), ("seller", "Seller"), ("admin", "Admin")],
                default="user",
                null=True,
            ),
        ),
    ]
