# Generated by Django 4.2.2 on 2023-07-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_isadmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="isAdmin",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
