# Generated by Django 4.2.2 on 2023-07-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
