# Generated by Django 4.2.2 on 2023-07-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_data",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="products_cart",
            field=models.ManyToManyField(
                related_name="cart_products",
                through="cart.CartProduct",
                to="products.product",
            ),
        ),
    ]
