# Generated by Django 4.2.2 on 2023-07-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pedido realizado", "Pedido Realizado"),
                            ("Em andamento", "Em Andamento"),
                            ("Entregue", "Entregue"),
                        ],
                        default="Pedido realizado",
                        max_length=25,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
