# Generated by Django 4.2.3 on 2023-07-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="seller_id",
            field=models.IntegerField(null=True),
        ),
    ]
