# Generated by Django 4.2.2 on 2023-07-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pedido realizado", "Pedido Realizado"),
                    ("Em andamento", "Em Andamento"),
                    ("Entregue", "Entregue"),
                ],
                default="Pedido realizado",
                max_length=25,
            ),
        ),
    ]
